"""add console pattern filtering

Revision ID: 1602215636b1
Revises: a5f2310fe213
Create Date: 2026-07-07 23:21:26.053567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1602215636b1'
down_revision: Union[str, None] = 'a5f2310fe213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('console_pattern_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('filter', 'event', name='consolepatternkind'), nullable=False),
    sa.Column('builtin_key', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('console_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('filter', 'event', name='consolepatternkind'), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'console_filter_mode',
                sa.Enum('off', 'blacklist', 'whitelist', name='consolefiltermode'),
                nullable=False,
                server_default='blacklist',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('console_filter_mode')

    op.drop_table('console_patterns')
    op.drop_table('console_pattern_overrides')
    # ### end Alembic commands ###
