"""add amp_instance_id to servers

Revision ID: 5461ef28bcbb
Revises: 6adf28ce6fc7
Create Date: 2026-07-05 15:30:23.204743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5461ef28bcbb'
down_revision: Union[str, None] = '6adf28ce6fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amp_instance_id', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint('uq_servers_amp_instance_id', ['amp_instance_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_servers_amp_instance_id', type_='unique')
        batch_op.drop_column('amp_instance_id')

    # ### end Alembic commands ###
