"""banner schema: server banner fields, banner groups, user donator flag

Revision ID: 890fb6f4b79f
Revises: 1602215636b1
Create Date: 2026-07-08 22:51:21.329274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890fb6f4b79f'
down_revision: Union[str, None] = '1602215636b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('banner_type', sa.Enum('embed', 'image', name='bannertype'), nullable=False),
    sa.Column('banner_theme', sa.String(length=50), nullable=True),
    sa.Column('banner_background_path', sa.String(length=255), nullable=True),
    sa.Column('banner_color_start', sa.String(length=7), nullable=True),
    sa.Column('banner_color_end', sa.String(length=7), nullable=True),
    sa.Column('banner_blur', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guilds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('banner_channel', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('banner_message_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('banner_type', sa.Enum('embed', 'image', name='bannertype'), nullable=False, server_default='embed'))
        batch_op.add_column(sa.Column('banner_theme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('banner_background_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('banner_color_start', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_color_end', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('banner_blur', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('steam_app_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('banner_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_servers_banner_group_id_banner_groups', 'banner_groups', ['banner_group_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_donator', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_donator')

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_servers_banner_group_id_banner_groups', type_='foreignkey')
        batch_op.drop_column('banner_group_id')
        batch_op.drop_column('steam_app_id')
        batch_op.drop_column('banner_blur')
        batch_op.drop_column('banner_color_end')
        batch_op.drop_column('banner_color_start')
        batch_op.drop_column('banner_background_path')
        batch_op.drop_column('banner_theme')
        batch_op.drop_column('banner_type')
        batch_op.drop_column('banner_message_id')
        batch_op.drop_column('banner_channel')
        batch_op.drop_column('banner_enabled')

    op.drop_table('banner_groups')
    # ### end Alembic commands ###
