"""add bannergroup layout field

Revision ID: 93ee847d2c8e
Revises: e2d8c8f88f9a
Create Date: 2026-07-10 00:09:16.345592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ee847d2c8e'
down_revision: Union[str, None] = 'e2d8c8f88f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('layout', sa.Enum('combined', 'separate', name='bannergrouplayout'), nullable=False, server_default='combined'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner_groups', schema=None) as batch_op:
        batch_op.drop_column('layout')

    # ### end Alembic commands ###
