"""moderation and whitelist schema additions

Revision ID: e067ea21d961
Revises: 5461ef28bcbb
Create Date: 2026-07-07 22:23:11.553073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e067ea21d961'
down_revision: Union[str, None] = '5461ef28bcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_message_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('escalation_reviewed', sa.Boolean(), nullable=False))

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_role_id', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('whitelist_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_message_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whitelist_requests', schema=None) as batch_op:
        batch_op.drop_column('review_message_id')

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('discord_role_id')

    with op.batch_alter_table('modlog', schema=None) as batch_op:
        batch_op.drop_column('escalation_reviewed')
        batch_op.drop_column('review_message_id')

    # ### end Alembic commands ###
