"""add banner_text_color to servers and banner_groups

Revision ID: e2d8c8f88f9a
Revises: 0730da7f01fc
Create Date: 2026-07-09 23:42:37.208053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d8c8f88f9a'
down_revision: Union[str, None] = '0730da7f01fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banner_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_text_color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_text_color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('banner_text_color')

    with op.batch_alter_table('banner_groups', schema=None) as batch_op:
        batch_op.drop_column('banner_text_color')

    # ### end Alembic commands ###
